# Generated by Django 5.1.6 on 2025-02-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='minor',
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
