# Generated by Django 5.1.6 on 2025-02-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidate_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='test_django_candidate',
        ),
    ]
