# Generated by Django 5.1.6 on 2025-02-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_candidate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='django_candidate',
        ),
    ]
