# Generated by Django 5.1.6 on 2025-02-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_alter_candidate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='test_django_candidate',
        ),
    ]
