# Generated by Django 5.1.6 on 2025-02-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('min_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_time', models.CharField(default='yearly', max_length=10)),
                ('posted_date', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('remote', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'django_jobs',
            },
        ),
    ]
