# Generated by Django 5.1.6 on 2025-02-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=500)),
                ('min_salary', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('salary_time', models.CharField(default='yearly', max_length=10)),
                ('posted_date', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(max_length=500)),
                ('remote', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'django_jobs',
            },
        ),
    ]
