# Generated by Django 5.1.6 on 2025-02-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_company_name_alter_job_job_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='test_django_jobs',
        ),
    ]
