# Generated by Django 5.1.6 on 2025-02-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='django_jobs',
        ),
    ]
