# Generated by Django 5.1.6 on 2025-03-09 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(help_text='Markdown content of the generated document')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cover_letters/%Y/%m/%d')),
                ('version', models.IntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gemini_cover_letter',
                'unique_together': {('user', 'job', 'profile', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(help_text='Markdown content of the generated document')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d')),
                ('version', models.IntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gemini_resume',
                'unique_together': {('user', 'job', 'profile', 'version')},
            },
        ),
    ]
